blueprint:
  name: Activar dispositivo por movimiento al atardecer dentro de un rango horario
  description: Este blueprint enciende una luz, un booleano o un switch seleccionado cuando se detecta movimiento en un sensor especificado. La automatización se activa a partir de un tiempo relativo a la puesta de sol, y se apaga después de un tiempo especificado en horas, minutos y segundos.
  domain: automation
  input:
    motion_sensor:
      name: Sensor de Movimiento
      description: Selecciona el sensor de movimiento que activará la automatización
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          
    target_device:
      name: Dispositivo para activar
      description: Selecciona el dispositivo que se activará cuando se detecte movimiento
      selector:
        target:
          entity:
            domain: 
              - light
              - switch
              - input_boolean

    offset_minutes:
      name: Minutos de ajuste respecto a la puesta de sol
      description: Ajuste de minutos antes (negativo) o después (positivo) de la puesta de sol para determinar la hora de inicio
      selector:
        number:
          min: -120
          max: 120
          unit_of_measurement: minutes
    
    end_time:
      name: Hora de fin
      description: Hora en la que dejará de ejecutarse la automatización
      selector:
        time:
    
    duration_hours:
      name: Horas de duración
      description: Cantidad de horas que el dispositivo permanecerá encendido
      selector:
        number:
          min: 0
          max: 23
          unit_of_measurement: hours

    duration_minutes:
      name: Minutos de duración
      description: Cantidad de minutos que el dispositivo permanecerá encendido
      selector:
        number:
          min: 0
          max: 59
          unit_of_measurement: minutes

    duration_seconds:
      name: Segundos de duración
      description: Cantidad de segundos que el dispositivo permanecerá encendido
      selector:
        number:
          min: 0
          max: 59
          unit_of_measurement: seconds

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: 'on'

condition:
  - condition: sun
    after_offset: !input offset_minutes
    after: sunset
  - condition: time
    before: !input end_time

action:
  - service: homeassistant.turn_on
    target: !input target_device
  - delay:
      hours: !input duration_hours
      minutes: !input duration_minutes
      seconds: !input duration_seconds
  - service: homeassistant.turn_off
    target: !input target_device
