blueprint:
  name: Activar dispositivo por movimiento con ajuste
  description: Este blueprint enciende un dispositivo (luz, interruptor, booleano) cuando se detecta movimiento, con ajustes relativos al atardecer (sunset).
  domain: automation
  input:
    motion_entity:
      name: Sensor de Movimiento
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    target_device:
      name: Dispositivo para activar
      description: Selecciona el dispositivo (luz, interruptor, etc.) que se activará cuando se detecte movimiento.
      selector:
        target:
          entity:
            domain:
              - light
              - switch
              - input_boolean
    sunset_offset:
      name: Offset para encender el dispositivo
      description: Define el offset en tiempo relativo al atardecer (sunset).
      default: "-12:00:00"
      selector:
        time: {}
    end_time:
      name: Hora de fin
      description: Hora en la que dejará de ejecutarse la automatización.
      default: "23:00:00"
      selector:
        time: {}
    no_motion_wait:
      name: Tiempo de espera sin movimiento.
      description: Tiempo en minutos para mantener el dispositivo encendido después del último movimiento detectado.
      default: 2
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: minutes
variables:
  expanded_entities: >
    {% set entity_list = [] %}
    {% for entity_id in expand('!input target_device') %}
      {% set entity_list = entity_list + [entity_id.entity_id] %}
    {% endfor %}
    {{ entity_list | join(', ') }}
  all_off: >
    {{ expand(expanded_entities) | selectattr('state', 'eq', 'off') | list | count == expanded_entities | count }}
trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"
condition:
  - condition: sun
    after: sunset
    after_offset: !input sunset_offset
  - condition: time
    before: !input end_time
  - condition: template
    value_template: "{{ all_off }}"
action:
  - service: persistent_notification.create
    data:
      message: >
        La automatización se ejecutó porque todas las luces estaban apagadas.
        Dispositivos y estados evaluados: {{ expanded_entities }}.
    title: "Depuración de Automatización"
  - service: homeassistant.turn_on
    target: !input target_device
  - delay:
      minutes: !input no_motion_wait
  - service: homeassistant.turn_off
    target: !input target_device
