blueprint:
  name: Activar dispositivo por movimiento con ajuste solar
  description: Este blueprint enciende un dispositivo (luz, interruptor, etc.) cuando se detecta movimiento, con ajustes relativos al atardecer (crepúsculo).
  domain: automation
  input:
    motion_entity:
      name: Sensor de Movimiento
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    target_device:
      name: Dispositivo para activar
      description: Selecciona el dispositivo (luz, interruptor, etc.) que se activará cuando se detecte movimiento
      selector:
        target:
          entity:
            domain:
              - light
              - switch

    no_motion_wait:
      name: Tiempo de espera sin movimiento
      description: Tiempo para mantener el dispositivo encendido después del último movimiento detectado.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

    sunset_offset:
      name: Offset para encender el dispositivo
      description: Define el offset en minutos relativo al atardecer
      default: 60
      selector:
        number:
          min: 0
          max: 240
          unit_of_measurement: minutes

    end_time:
      name: Hora de fin
      description: Hora en la que dejará de ejecutarse la automatización
      selector:
        time:

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

condition:
  - condition: sun
    after: sunset
    after_offset: !input sunset_offset
  - condition: time
    before: !input end_time

action:
  - service: homeassistant.turn_on
    target: !input target_device
  - wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      to: "off"
  - delay: !input no_motion_wait
  - service: homeassistant.turn_off
    target: !input target_device
