blueprint:
  name: Prueba Directa con `entity_id` Corregida
  description: Prueba directa usando `entity_id` sin mostrar el estado.
  domain: automation
  input:
    target_entity:
      name: Entidad para activar
      description: Selecciona una entidad específica (luz, interruptor, etc.).
      selector:
        entity:
          domain:
            - light
            - switch
            - input_boolean
trigger:
  platform: homeassistant
  event: start
action:
  - service: persistent_notification.create
    data:
      message: >
        Prueba con `entity_id` corregida.
        ID de la entidad seleccionada: !input target_entity.


