blueprint:
  name: Depuración de Entidades
  description: Prueba para verificar la captura de luces o enchufes seleccionados.
  domain: automation
  input:
    light_entities:
      name: Luces para activar
      description: Selecciona las luces que se activarán cuando se detecte movimiento.
      selector:
        target:
          entity:
            domain: light
    switch_entities:
      name: Enchufes para activar
      description: Selecciona los enchufes que se activarán cuando se detecte movimiento.
      selector:
        target:
          entity:
            domain: switch
trigger:
  platform: homeassistant
  event: start
action:
  - service: persistent_notification.create
    data:
      message: >
        Prueba de luces y enchufes.
        Luces seleccionadas: {{ expand('!input light_entities') }}.
        Enchufes seleccionados: {{ expand('!input switch_entities') }}.


