blueprint:
  name: Notificación de dispositivos seleccionados
  description: Selecciona múltiples dispositivos (luz, interruptor, input_boolean) y muestra una notificación persistente con los dispositivos seleccionados.
  domain: automation
  input:
    target_device:
      name: Dispositivos para notificación
      description: Selecciona los dispositivos (luces, interruptores, input_booleans) que se incluirán en la notificación.
      selector:
        target:
          entity:
            domain:
              - light
              - switch
              - input_boolean

trigger:
  - platform: state
    entity_id: !input target_device

variables:
  selected_devices: !input target_device.entity_id
  changed_device: "{{ trigger.entity_id }}"
  device_names: >
    {% set names = [] %}
    {% for device in selected_devices %}
      {% set names = names + [states[device].name] %}
    {% endfor %}
    {{ names | join(', ') }}

action:
  - service: persistent_notification.create
    data:
      title: "Dispositivos Seleccionados"
      message: >
        Los siguientes dispositivos fueron seleccionados:
        {{ device_names }}
      notification_id: 'selected_devices_notification'


