blueprint:
  name: Notificación de dispositivos seleccionados
  description: Selecciona múltiples dispositivos de tipo luz o switch y muestra una notificación persistente con los dispositivos seleccionados.
  domain: automation
  input:
    devices:
      name: Dispositivos (luces o switches)
      description: Selecciona los dispositivos de tipo luz o switch.
      selector:
        entity:
          domain: light, switch
          multiple: true

trigger:
  - platform: state
    entity_id: !input devices

variables:
  selected_devices: !input devices
  changed_device: "{{ trigger.entity_id }}"
  device_names: >
    {% set names = [] %}
    {% for device in selected_devices %}
      {% set names = names + [states[device].name] %}
    {% endfor %}
    {{ names | join(', ') }}

action:
  - service: persistent_notification.create
    data:
      title: "Dispositivos Seleccionados"
      message: >
        Los siguientes dispositivos fueron seleccionados:
        {{ device_names }}
      notification_id: 'selected_devices_notification'

