blueprint:
  name: Prueba Directa de `expand`
  description: Prueba para verificar si `expand` funciona con entidades seleccionadas.
  domain: automation
  input:
    target_device:
      name: Dispositivo para activar
      description: Selecciona el dispositivo (luz, interruptor, etc.) que se evaluará.
      selector:
        target:
          entity:
            domain:
              - light
              - switch
              - input_boolean
trigger:
  platform: homeassistant
  event: start
action:
  - service: persistent_notification.create
    data:
      message: >
        Prueba de `expand`.
        Resultado de `expand`: {{ expand('!input target_device') }}.
