blueprint:
  name: Prueba Directa con `entity_id`
  description: Prueba directa usando `entity_id`.
  domain: automation
  input:
    target_entity:
      name: Entidad para activar
      description: Selecciona una entidad específica (luz, interruptor, etc.).
      selector:
        entity:
          domain:
            - light
            - switch
            - input_boolean
trigger:
  platform: homeassistant
  event: start
action:
  - service: persistent_notification.create
    data:
      message: >
        Prueba con `entity_id`.
        Entidad seleccionada: {{ states('!input target_entity') }}.

