blueprint:
  name: Notificación de dispositivos seleccionados
  description: Selecciona múltiples dispositivos de tipo luz o switch y muestra una notificación persistente con los dispositivos seleccionados.
  domain: automation
  input:
    devices:
      name: Dispositivos (luces o switches)
      description: Selecciona los dispositivos de tipo luz o switch.
      selector:
        target:
          entity:
            domain: light, switch
  trigger:
    platform: state
    entity_id: !input devices
  action:
    - service: persistent_notification.create
      data:
        title: 'Dispositivos Seleccionados'
        message: >
          Has seleccionado los siguientes dispositivos:
          {% for entity_id in target.entities %}
            - {{ states[entity_id].name }}
          {% endfor %}
        notification_id: 'selected_devices_notification'

