blueprint:
  name: Control de Luces y Enchufes con Movimiento
  description: Enciende luces y enchufes cuando se detecta movimiento, con ajustes relativos al atardecer (sunset).
  domain: automation
  input:
    motion_entity:
      name: Sensor de Movimiento
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_entities:
      name: Luces para activar
      description: Selecciona las luces que se activarán cuando se detecte movimiento.
      selector:
        target:
          entity:
            domain: light
    switch_entities:
      name: Enchufes para activar
      description: Selecciona los enchufes que se activarán cuando se detecte movimiento.
      selector:
        target:
          entity:
            domain: switch
    sunset_offset:
      name: Offset para encender las entidades
      description: Define el offset en tiempo relativo al atardecer (sunset).
      default: "-12:00:00"
      selector:
        time: {}
    end_time:
      name: Hora de fin
      description: Hora en la que dejará de ejecutarse la automatización.
      default: "23:00:00"
      selector:
        time: {}
    no_motion_wait:
      name: Tiempo de espera sin movimiento
      description: Tiempo en minutos para mantener las entidades encendidas después del último movimiento detectado.
      default: 2
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: minutes
variables:
  light_ids: !input light_entities
  switch_ids: !input switch_entities
  open_lights: "{{ expand(light_ids) | selectattr('state', 'eq', 'off') | map(attribute='entity_id') | list }}"
  open_switches: "{{ expand(switch_ids) | selectattr('state', 'eq', 'off') | map(attribute='entity_id') | list }}"
trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"
condition:
  - condition: sun
    after: sunset
    after_offset: !input sunset_offset
  - condition: time
    before: !input end_time
action:
  - service: persistent_notification.create
    data:
      message: >
        Luces seleccionadas para encender: {{ open_lights }}.
        Enchufes seleccionados para encender: {{ open_switches }}.
  - service: light.turn_on
    target:
      entity_id: "{{ open_lights }}"
  - service: switch.turn_on
    target:
      entity_id: "{{ open_switches }}"
  - delay:
      minutes: !input no_motion_wait
  - service: light.turn_off
    target:
      entity_id: "{{ open_lights }}"
  - service: switch.turn_off
    target:
      entity_id: "{{ open_switches }}"
