blueprint:
  name: Activar dispositivo por movimiento con ajuste solar
  description: Enciende un interruptor y/o luz cuando se detecta movimiento, con ajustes relativos al amanecer y atardecer.
  domain: automation
  input:
    motion_entity:
      name: Sensor de Movimiento
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    switch_target:
      name: Interruptor
      default: {}
      selector:
        target:
          entity:
            domain: switch
    light_target:
      name: Luz
      default: {}
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Tiempo de espera sin movimiento
      description: Tiempo para mantener el dispositivo encendido después del último movimiento detectado.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    sunset_offset:
      name: Offset para encender las luces
      description: Definir el offset relativo al atardecer
      default: 60
      selector:
        number:
          min: 0
          max: 240
          unit_of_measurement: minutes
    sunrise_offset:
      name: Offset para apagar las luces
      description: Definir el offset relativo al amanecer
      default: 45
      selector:
        number:
          min: 0
          max: 240
          unit_of_measurement: minutes

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

condition:
  - condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: !input sunset_offset
      - condition: sun
        before: sunrise
        before_offset: !input sunrise_offset

action:
  - choose:
      - conditions: "{{ light_target|length > 0 and switch_target|length > 0 }}"
        sequence:
          - service: switch.turn_on
            target: !input switch_target
          - service: light.turn_on
            target: !input light_target
          - wait_for_trigger:
              - platform: state
                entity_id: !input motion_entity
                to: 'off'
          - delay: !input no_motion_wait
          - service: switch.turn_off
            target: !input switch_target
          - service: light.turn_off
            target: !input light_target
      - conditions: "{{ switch_target|length > 0 }}"
        sequence:
          - service: switch.turn_on
            target: !input switch_target
          - wait_for_trigger:
              - platform: state
                entity_id: !input motion_entity
                to: 'off'
          - delay: !input no_motion_wait
          - service: switch.turn_off
            target: !input switch_target
      - conditions: "{{ light_target|length > 0 }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
          - wait_for_trigger:
              - platform: state
                entity_id: !input motion_entity
                to: 'off'
          - delay: !input no_motion_wait
          - service: light.turn_off
            target: !input light_target
    default: []
