blueprint:
  name: Prueba Directa con `entity_id` Corregida y Mejorada
  description: Prueba directa para mostrar el ID de la entidad seleccionada correctamente.
  domain: automation
  input:
    target_entity:
      name: Entidad para activar
      description: Selecciona una entidad específica (luz, interruptor, etc.).
      selector:
        entity:
          domain:
            - light
            - switch
            - input_boolean
trigger:
  platform: homeassistant
  event: start
action:
  - service: persistent_notification.create
    data:
      message: >
        Prueba con `entity_id` corregida y mejorada.
        ID de la entidad seleccionada: {{ target_entity }}.
variables:
  target_entity: !input target_entity
