blueprint:
  name: Activar dispositivo por movimiento con ajuste
  description: Este blueprint enciende un dispositivo (luz, interruptor, booleano) cuando se detecta movimiento, con ajustes relativos al atardecer (sunset)
  domain: automation
  input:
    motion_entity:
      name: Sensor de Movimiento
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    target_device:
      name: Dispositivo para activar
      description: Selecciona el dispositivo (luz, interruptor, etc.) que se activará cuando se detecte movimiento
      selector:
        target:
          entity:
            domain:
              - light
              - switch
              - input_boolean
    sunset_offset:
      name: Offset para encender el dispositivo
      description: Define el offset en minutos relativo al atardecer (sunset)
      default: "-1:00:00"
      selector:
        number:
          min: -120
          max: 120
          unit_of_measurement: minutes
    end_time:
      name: Hora de fin
      description: Hora en la que dejará de ejecutarse la automatización
      default: "23:00:00"
      selector:
        time: {}
    no_motion_wait:
      name: Tiempo de espera sin movimiento
      description: Tiempo en minutos para mantener el dispositivo encendido después del último movimiento detectado.
      default: 2
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: minutes
variables:
  target_entities: >
    {{ expand('!input target_device') | map(attribute='entity_id') | list }}
  sensors: >
    {% set result = namespace(sensors=[]) %}
    {% for entity_id in target_entities %}
      {% if states(entity_id) == 'off' %}
        {% set result.sensors = result.sensors + [entity_id] %}
      {% endif %}
    {% endfor %}
    {{ result.sensors }}
trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"
condition:
  - condition: sun
    after: sunset
    after_offset: !input sunset_offset
  - condition: time
    before: !input end_time
  - condition: template
    value_template: >
      {{ sensors | length == target_entities | length }}
action:
  - service: persistent_notification.create
    data:
      message: "La automatización se ejecutó con los dispositivos apagados: {{ sensors | join(', ') }}."
      title: "Depuración de Automatización"
  - service: homeassistant.turn_on
    target: !input target_device
  - delay:
      minutes: !input no_motion_wait
  - service: homeassistant.turn_off
    target: !input target_device
